acm_id: null
announcements:
  enabled: true
  limit: 5
  scrollable: true
back_to_top: true
baseurl: ''
bib_search: true
bing_site_verification: null
blog_description: A simple blog discussing the latest research on my team
blog_name: LogDS Blog
blogger_url: null
bluesky_url: null
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /:collection/:title/
  projects:
    output: true
    permalink: /:collection/:title/
contact_note: 'You can even add a little note about which of these is the best way
  to reach you.

  '
cronitor_analytics: null
dblp_url: null
defaults:
- scope:
    path: assets
  values:
    sitemap: false
description: 'A simple, whitespace theme for academics. Based on [*folio](https://github.com/bogoli/-folio)
  design.

  '
discord_id: null
display_categories:
- external-services
display_tags:
- statecharts
disqus_shortname: LogDS
email: bergamigiacomo@gmail.com
enable_bing_verification: false
enable_cronitor_analytics: false
enable_darkmode: true
enable_google_analytics: true
enable_google_verification: false
enable_masonry: true
enable_math: true
enable_medium_zoom: true
enable_navbar_social: false
enable_pirsch_analytics: false
enable_progressbar: true
enable_project_categories: true
enable_publication_badges:
  altmetric: true
  dimensions: true
  google_scholar: true
  inspirehep: true
enable_publication_thumbnails: true
enable_tooltips: false
enable_video_embedding: false
exclude:
- bin/
- CONTRIBUTING.md
- CUSTOMIZE.md
- Dockerfile
- docker-compose.yml
- docker-compose-slim.yml
- FAQ.md
- Gemfile
- Gemfile.lock
- INSTALL.md
- LICENSE
- lighthouse_results/
- package.json
- package-lock.json
- _pages/about_einstein.md
- purgecss.config.js
- README.md
- readme_preview/
- vendor
external_links:
  enabled: true
  exclude: null
  rel: external nofollow noopener
  target: _blank
facebook_id: null
filtered_bibtex_keywords:
- abbr
- abstract
- additional_info
- altmetric
- annotation
- arxiv
- award
- award_name
- bibtex_show
- blog
- code
- google_scholar_id
- html
- inspirehep_id
- pdf
- poster
- preview
- selected
- slides
- supp
- video
- website
first_name: Giacomo
flickr_id: null
footer_fixed: true
footer_text: 'Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a>
  with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme. Hosted
  by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>. Photos
  from <a href="https://unsplash.com" target="_blank">Unsplash</a>.

  '
giscus:
  category: Comments
  category_id: null
  emit_metadata: 0
  input_position: bottom
  lang: en
  mapping: title
  reactions_enabled: 1
  repo: null
  repo_id: null
  strict: 1
  theme: preferred_color_scheme
github_username: jackbergus
gitlab_username: null
google_analytics: null
google_site_verification: null
highlighter: rouge
icon: "ðŸ“š"
ieee_id: null
imagemagick:
  enabled: true
  input_directories:
  - assets/img/
  input_formats:
  - .jpg
  - .jpeg
  - .png
  - .tiff
  - .gif
  output_formats:
    webp: -quality 85
  widths:
  - 480
  - 800
  - 1400
impressum_path: null
include:
- _pages
inspirehep_id: null
instagram_id: null
jekyll-archives:
  enabled:
  - year
  - tags
  - categories
  layouts:
    category: archive-category
    tag: archive-tag
    year: archive-year
  permalinks:
    category: /blog/category/:name/
    tag: /blog/tag/:name/
    year: /blog/:year/
jekyll-minifier:
  exclude:
  - robots.txt
  - assets/js/search/*.js
  uglifier_args:
    harmony: true
jekyll_get_json:
- data: resume
  json: assets/json/resume.json
jsonresume:
- basics
- work
- education
- publications
- projects
- volunteer
- awards
- certificates
- skills
- languages
- interests
- references
kaggle_id: null
keep_files:
- CNAME
- .nojekyll
keybase_username: null
keywords: jekyll, jekyll-theme, academic-website, portfolio-website
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: false
      start_line: 1
    css_class: highlight
    span:
      line_numbers: false
lang: en
last_name: Bergami
last_updated: false
lastfm_id: null
latest_posts:
  enabled: true
  limit: 3
  scrollable: true
lattes_id: null
lazy_loading_images: true
linkedin_username: bergami
lsi: false
markdown: kramdown
mastodon_username: null
max_author_limit: 3
max_width: 930px
medium_username: null
more_authors_animation_delay: 10
navbar_fixed: true
newsletter:
  enabled: false
  endpoint: null
og_image: null
orcid_id: null
osf_id: null
pagination:
  enabled: true
permalink: /blog/:year/:title/
pinterest_id: null
pirsch_analytics: null
plugins:
- jekyll-archives
- jekyll-email-protect
- jekyll-feed
- jekyll-get-json
- jekyll-imagemagick
- jekyll-jupyter-notebook
- jekyll-link-attributes
- jekyll-minifier
- jekyll-paginate-v2
- jekyll-regex-replace
- jekyll/scholar
- jekyll-sitemap
- jekyll-tabs
- jekyll-toc
- jekyll-twitter-plugin
- jemoji
publons_id: null
quora_username: null
related_blog_posts:
  enabled: true
  max_related: 5
repo_theme_dark: dark
repo_theme_light: default
repo_trophies:
  enabled: false
  theme_dark: gitdimmed
  theme_light: flat
research_gate_profile: null
rss_icon: true
sass:
  style: compressed
scholar:
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters:
  - latex
  - smallcaps
  - superscript
  details_dir: bibliography
  details_link: Details
  first_name:
  - Giacomo
  - 'Giacomo '
  - G.
  group_by: year
  group_order: descending
  join_strings: true
  last_name:
  - Bergami
  locale: en
  query: '@*'
  replace_strings: true
  source: /_bibliography/
  style: apa
scholar_userid: W2Uk0xwAAAAJ
scopus_id: null
search_enabled: true
semanticscholar_id: null
serve_og_meta: false
serve_schema_org: false
socials_in_search: true
spotify_id: null
stackoverflow_id: null
telegram_username: null
third_party_libraries:
  bootstrap-table:
    integrity:
      css: sha256-uRX+PiRTR4ysKFRCykT8HLuRCub26LgXJZym3Yeom1c=
      js: sha256-4rppopQE9POKfukn2kEvhJ9Um25Cf6+IDVkARD0xh78=
    url:
      css: https://cdn.jsdelivr.net/npm/bootstrap-table@{{version}}/dist/bootstrap-table.min.css
      js: https://cdn.jsdelivr.net/npm/bootstrap-table@{{version}}/dist/bootstrap-table.min.js
    version: 1.22.4
  chartjs:
    integrity:
      js: sha256-0q+JdOlScWOHcunpUk21uab1jW7C1deBQARHtKMcaB4=
    url:
      js: https://cdn.jsdelivr.net/npm/chart.js@{{version}}/dist/chart.umd.min.js
    version: 4.4.1
  d3:
    integrity:
      js: sha256-1rA678n2xEx7x4cTZ5x4wpUCj6kUMZEZ5cxLSVSFWxw=
    url:
      js: https://cdn.jsdelivr.net/npm/d3@{{version}}/dist/d3.min.js
    version: 7.8.5
  diff2html:
    integrity:
      css: sha256-IMBK4VNZp0ivwefSn51bswdsrhk0HoMTLc2GqFHFBXg=
      js: sha256-eU2TVHX633T1o/bTQp6iIJByYJEtZThhF9bKz/DcbbY=
    url:
      css: https://cdn.jsdelivr.net/npm/diff2html@{{version}}/bundles/css/diff2html.min.css
      js: https://cdn.jsdelivr.net/npm/diff2html@{{version}}/bundles/js/diff2html-ui.min.js
    version: 3.4.47
  download: false
  echarts:
    integrity:
      js:
        dark_theme: sha256-sm6Ui9w41++ZCWmIWDLC18a6ki72FQpWDiYTDxEPXwU=
        library: sha256-QvgynZibb2U53SsVu98NggJXYqwRL7tg3FeyfXvPOUY=
    url:
      js:
        dark_theme: https://cdn.jsdelivr.net/npm/echarts@{{version}}/theme/dark-fresh-cut.js
        library: https://cdn.jsdelivr.net/npm/echarts@{{version}}/dist/echarts.min.js
    version: 5.5.0
  google_fonts:
    url:
      fonts: https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:100,300,400,500,700|Material+Icons&display=swap
  highlightjs:
    integrity:
      css:
        dark: sha256-nyCNAiECsdDHrr/s2OQsp5l9XeY2ZJ0rMepjCT2AkBk=
        light: sha256-Oppd74ucMR5a5Dq96FxjEzGF7tTw2fZ/6ksAqDCM8GY=
    url:
      css:
        dark: https://cdn.jsdelivr.net/npm/highlight.js@{{version}}/styles/github-dark.min.css
        light: https://cdn.jsdelivr.net/npm/highlight.js@{{version}}/styles/github.min.css
    version: 11.9.0
  imagesloaded:
    integrity:
      js: sha256-htrLFfZJ6v5udOG+3kNLINIKh2gvoKqwEhHYfTTMICc=
    url:
      js: https://cdn.jsdelivr.net/npm/imagesloaded@{{version}}/imagesloaded.pkgd.min.js
    version: 5.0.0
  img-comparison-slider:
    integrity:
      css: sha256-3qTIuuUWIFnnU3LpQMjqiXc0p09rvd0dmj+WkpQXSR8=
      js: sha256-EXHg3x1K4oIWdyohPeKX2ZS++Wxt/FRPH7Nl01nat1o=
      map: sha256-3wfqS2WU5kGA/ePcgFzJXl5oSN1QsgZI4/edprTgX8w=
    url:
      css: https://cdn.jsdelivr.net/npm/img-comparison-slider@{{version}}/dist/styles.min.css
      js: https://cdn.jsdelivr.net/npm/img-comparison-slider@{{version}}/dist/index.min.js
      map: https://cdn.jsdelivr.net/npm/img-comparison-slider@{{version}}/dist/index.js.map
    version: 8.0.6
  jquery:
    integrity:
      js: sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=
    url:
      js: https://cdn.jsdelivr.net/npm/jquery@{{version}}/dist/jquery.min.js
    version: 3.6.0
  leaflet:
    integrity:
      css: sha256-q9ba7o845pMPFU+zcAll8rv+gC+fSovKsOoNQ6cynuQ=
      js: sha256-MgH13bFTTNqsnuEoqNPBLDaqxjGH+lCpqrukmXc8Ppg=
      js_map: sha256-YAoQ3FzREN4GmVENMir8vgHHypC0xfSK3CAxTHCqx1M=
    local:
      images: images/
    url:
      css: https://cdn.jsdelivr.net/npm/leaflet@{{version}}/dist/leaflet.min.css
      images: https://cdn.jsdelivr.net/npm/leaflet@{{version}}/dist/images/
      js: https://cdn.jsdelivr.net/npm/leaflet@{{version}}/dist/leaflet.min.js
      js_map: https://cdn.jsdelivr.net/npm/leaflet@{{version}}/dist/leaflet.js.map
    version: 1.9.4
  masonry:
    integrity:
      js: sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI=
    url:
      js: https://cdn.jsdelivr.net/npm/masonry-layout@{{version}}/dist/masonry.pkgd.min.js
    version: 4.2.2
  mathjax:
    integrity:
      js: sha256-MASABpB4tYktI2Oitl4t+78w/lyA+D7b/s9GEP0JOGI=
    local:
      fonts: output/chtml/fonts/woff-v2/
    url:
      fonts: https://cdn.jsdelivr.net/npm/mathjax@{{version}}/es5/output/chtml/fonts/woff-v2/
      js: https://cdn.jsdelivr.net/npm/mathjax@{{version}}/es5/tex-mml-chtml.js
    version: 3.2.2
  mdb:
    integrity:
      css: sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw=
      css_map: sha256-iYYMNfsJdVZjvsebJulg09miBXM4/GMTJgv1u5EZFFM=
      js: sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA=
      js_map: sha256-UPgyn4YNsT0khkBK5553QwhnlbTlU0aa+igyc6qP1bE=
    url:
      css: https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/css/mdb.min.css
      css_map: https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/css/mdb.min.css.map
      js: https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/js/mdb.min.js
      js_map: https://cdn.jsdelivr.net/npm/mdbootstrap@{{version}}/js/mdb.min.js.map
    version: 4.20.0
  medium_zoom:
    integrity:
      js: sha256-ZgMyDAIYDYGxbcpJcfUnYwNevG/xi9OHKaR/8GK+jWc=
    url:
      js: https://cdn.jsdelivr.net/npm/medium-zoom@{{version}}/dist/medium-zoom.min.js
    version: 1.1.0
  mermaid:
    integrity:
      js: sha256-TtLOdUA8mstPoO6sGvHIGx2ceXrrX4KgIItO06XOn8A=
    url:
      js: https://cdn.jsdelivr.net/npm/mermaid@{{version}}/dist/mermaid.min.js
    version: 10.7.0
  polyfill:
    url:
      js: https://cdnjs.cloudflare.com/polyfill/v{{version}}/polyfill.min.js?features=es6
    version: '3'
  pseudocode:
    integrity:
      css: sha256-VwMV//xgBPDyRFVSOshhRhzJRDyBmIACniLPpeXNUdc=
      js: sha256-aVkDxqyzrB+ExUsOY9PdyelkDhn/DfrjWu08aVpqNlo=
    url:
      css: https://cdn.jsdelivr.net/npm/pseudocode@{{version}}/build/pseudocode.min.css
      js: https://cdn.jsdelivr.net/npm/pseudocode@{{version}}/build/pseudocode.min.js
    version: 2.4.1
  swiper:
    integrity:
      css: sha256-yUoNxsvX+Vo8Trj3lZ/Y5ZBf8HlBFsB6Xwm7rH75/9E=
      js: sha256-BPrwikijIybg9OQC5SYFFqhBjERYOn97tCureFgYH1E=
      map: sha256-lbF5CsospW93otqvWOIbbhj80CjazrZXvamD7nC7TBI=
    url:
      css: https://cdn.jsdelivr.net/npm/swiper@{{version}}/swiper-bundle.min.css
      js: https://cdn.jsdelivr.net/npm/swiper@{{version}}/swiper-element-bundle.min.js
      map: https://cdn.jsdelivr.net/npm/swiper@{{version}}/swiper-element-bundle.min.js.map
    version: 11.0.5
  swiper-map:
    integrity:
      js: sha256-hlZaH8ySXX97bZaetnrtYlKuhx3oEXFz/s2IXchu6vk=
    url:
      js: https://cdn.jsdelivr.net/npm/swiper@11.1.0/swiper-element-bundle.min.js.map
    version: 11.0.5
  vega:
    integrity:
      js: sha256-Yot/cfgMMMpFwkp/5azR20Tfkt24PFqQ6IQS+80HIZs=
      js_map: sha256-z0x9ICA65dPkZ0JVa9wTImfF6n7AJsKc6WlFE96/wNA=
    url:
      js: https://cdn.jsdelivr.net/npm/vega@{{version}}/build/vega.min.js
      js_map: https://cdn.jsdelivr.net/npm/vega@{{version}}/build/vega.min.js.map
    version: 5.27.0
  vega-embed:
    integrity:
      js: sha256-FPCJ9JYCC9AZSpvC/t/wHBX7ybueZhIqOMjpWqfl3DU=
      js_map: sha256-VBbfSEFYSMdX/rTdGrONEHNP6BprCB7H/LpMMNt/cPA=
    url:
      js: https://cdn.jsdelivr.net/npm/vega-embed@{{version}}/build/vega-embed.min.js
      js_map: https://cdn.jsdelivr.net/npm/vega-embed@{{version}}/build/vega-embed.min.js.map
    version: 6.24.0
  vega-lite:
    integrity:
      js: sha256-TvBvIS5jUN4BSy009usRjNzjI1qRrHPYv7xVLJyjUyw=
      js_map: sha256-l2I4D5JC23Ulsu6e3sKVe5AJ+r+DFkzkKnZS8nUGz28=
    url:
      js: https://cdn.jsdelivr.net/npm/vega-lite@{{version}}/build/vega-lite.min.js
      js_map: https://cdn.jsdelivr.net/npm/vega-lite@{{version}}/build/vega-lite.min.js.map
    version: 5.16.3
title: blank
unsplash_id: null
url: https://logds.github.io
wechat_qr: null
whatsapp_number: null
wikidata_id: null
wikipedia_id: null
work_url: null
x_username: gyankos
youtube_id: null
zotero_username: null
